### PR TITLE
Add persistence examples.

### PR DESCRIPTION
**Pull request by irumiha**
This PR adds two persistence examples. One is using Hibernate and another is using [Magnum](https://github.com/AugustNagro/magnum).

### CODE REVIEW

**Comment by carlosedp** [comment]
That's pretty neat! I'll try to rebase and merge from Github itself due to last two commits.

**Comment by carlosedp** [comment]
Unfortunately I can't rebase and merge... could you please rebase and push again?
Thanks a lot and let's keep up this repo :)

**Comment by carlosedp** [comment]
I've rebased locally and will merge right now! Do you think it's possible to add some test cases to the new code? This would make easy to improve later.
Again, thanks a lot!

**Comment by irumiha** [comment]
Thank you. All my recent projects were using squash+merge strategy so I didn't remember to ask.

**Pull request merged**
