### PR TITLE
Persistence tests and minimal UI

### PR DESCRIPTION
**Pull request by irumiha**
This PR adds the minimal set of persistence tests and a basic example of using Qute templates. I also added the minimal HTMX enhancement  into the mix, to make the pages "modern" :smile:

### CODE REVIEW

**Comment by carlosedp** [comment]
Thanks! That's very neat... I might replace the list with a table in the view :)

Thanks a lot for the help... I'm thinking about creating a Scala landing page in Quarkus similar to the Kotlin one (https://quarkus.io/guides/kotlin)... this would point users to this quickstart and give ideas on how to use Scala...

BTW, I'm loving the way Quarkus works... :)

**Comment by irumiha** [comment]
Quarkus dev experience reminds me of Playframework, only more polished (that's what you get when you have a larger, paid team working on it).

With Scala there are some pitfalls. 
- Panache persistence is impossible to use because it depends on static classes and Java annotation processors.
- Qute typechecked templates are impossible because it also uses tricks with Java static classes and native methods. At least the method I used works (placing the datatype declaration at the top of the template).
- many integrations, such as Qute templates expect Java collections so you have to convert. 

All in all Scala support is very barebones, as much as I liked this excercise I wouldn't build my next project with this combo, at this stage of development.

**Comment by carlosedp** [comment]
Thanks a lot for your insights... I understand Quarkus authors wrote some abstraction layer and modules to provide this for Kotlin, right?
I see something like `quarkus-hibernate-orm-panache-kotlin` and so on...

**Comment by irumiha** [comment]
Yes, proper integration should have some specific modules that adds support for Scala, like for Kotlin. Apart from that, it would be great to carefully document what works and what doesn't. 
Looking at this quickstart, it is obvious that you can build a functioning application, but it would save people some trouble if they know to stay away from some areas.

**Pull request merged**
